import io
import os
import uuid
import tempfile
from datetime import datetime
from fpdf import FPDF
from PIL import Image

class MedicalReport(FPDF):
    def header(self):
        # Blue Banner
        self.set_fill_color(66, 135, 245) # Royal Blue
        self.rect(0, 0, 210, 40, 'F')
        
        # Title
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 24)
        self.set_xy(10, 10)
        self.cell(0, 10, 'Histopathology Analysis Report', 0, 1, 'L')
        
        self.set_font('Arial', '', 12)
        self.set_xy(10, 22)
        self.cell(0, 10, 'Oral Cancer AI Platform', 0, 1, 'L')
        
        # Logo/Icon placeholder (Right side)
        self.set_font('Arial', 'B', 30)
        self.set_xy(170, 10)
        self.cell(30, 20, '+', 0, 0, 'C') # Simple Plus sign as logo
        
        # Ensure content starts below the banner
        self.set_y(50)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by OralAI Platform', 0, 0, 'C')

    def section_header(self, title):
        self.set_fill_color(100, 149, 237) # Lighter Blue
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, f"  {title}", 0, 1, 'L', 1)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def data_row(self, label, value, fill=False):
        self.set_font('Arial', 'B', 10)
        if fill:
            self.set_fill_color(240, 248, 255) # Very light blue
        else:
            self.set_fill_color(255, 255, 255)
        
        # Label
        self.cell(60, 8, f"  {label}", 1, 0, 'L', fill)
        
        # Value
        self.set_font('Arial', '', 10)
        self.cell(0, 8, f"  {str(value)}", 1, 1, 'L', fill)

def generate_expert_report(data: dict, image_bytes: bytes = None) -> bytes:
    """
    Generates a formal medical PDF report for Histopathology (Model A).
    """
    # Normalize data
    if "final_analysis" in data:
        data = data["final_analysis"]
    
    predictions = data.get("predictions", {})
    
    pdf = MedicalReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # 1. Patient/Sample Demographics (Mocked structure)
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Sample Information", 0, 1, 'L')
    
    # Create a grid-like table for demographics
    pdf.set_font('Arial', '', 10)
    
    # Row 1
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(30, 8, " Sample ID", 1, 0, 'L', 1)
    pdf.cell(65, 8, f" {data.get('sample_id', 'N/A')}", 1, 0, 'L')
    pdf.cell(30, 8, " Date", 1, 0, 'L', 1)
    pdf.cell(65, 8, f" {datetime.now().strftime('%Y-%m-%d')}", 1, 1, 'L')
    
    # Row 2
    pdf.cell(30, 8, " Modality", 1, 0, 'L', 1)
    pdf.cell(65, 8, " Histopathology (Microscopic)", 1, 0, 'L')
    pdf.cell(30, 8, " AI Model", 1, 0, 'L', 1)
    pdf.cell(65, 8, " Model A (Deep Learning)", 1, 1, 'L')
    
    pdf.ln(10)
    
    # 2. Diagnostic Metrics
    pdf.section_header("Diagnostic Metrics")
    
    metrics = [
        ("Tumour Detected", "YES" if predictions.get("tumour_detected") else "NO"),
        ("Tumour Probability", f"{predictions.get('tumour_probability', 0) * 100:.1f}%"),
        ("Depth of Invasion", f"{predictions.get('depth_of_invasion_mm', 'N/A')} mm"),
        ("Pattern of Invasion", f"Type {predictions.get('pattern_of_invasion', 'N/A')}"),
        ("Perineural Invasion", "Present" if predictions.get("perineural_invasion") else "Absent"),
        ("Tumour Buds Count", str(predictions.get("tumour_buds_count", "N/A"))),
        ("Mitotic Figures", str(predictions.get("mitotic_figures_count", "N/A")))
    ]
    
    for i, (label, value) in enumerate(metrics):
        pdf.data_row(label, value, fill=(i % 2 == 0))
        
    pdf.ln(10)
    
    # 3. Visual Analysis
    if image_bytes:
        pdf.section_header("Visual Analysis")
        pdf.ln(2)
        
        # Use a local temp file to avoid Windows permission/path issues with AppData
        temp_dir = os.path.join(os.getcwd(), "temp_reports")
        os.makedirs(temp_dir, exist_ok=True)
        tmp_path = os.path.join(temp_dir, f"expert_{uuid.uuid4()}.jpg")
        
        try:
            # Convert image to JPEG using Pillow to ensure FPDF compatibility
            # This handles WebP, PNG, etc.
            with Image.open(io.BytesIO(image_bytes)) as img:
                # Convert to RGB (remove alpha channel if present)
                rgb_img = img.convert('RGB')
                rgb_img.save(tmp_path, format='JPEG')
                
                w, h = rgb_img.size
                aspect = h / w
            
            target_w = 120  # Reduced width
            target_h = target_w * aspect
            
            # Check if image fits on page, else add page
            if pdf.get_y() + target_h > 250: 
                pdf.add_page()
            
            # Center the image
            x_pos = (210 - target_w) / 2
            pdf.image(tmp_path, x=x_pos, w=target_w)
            pdf.ln(target_h + 5) # Move cursor past image
            
        except Exception as e:
            pdf.cell(0, 10, f"Error loading image: {str(e)}", 1, 1)
        finally:
            if os.path.exists(tmp_path):
                try:
                    os.remove(tmp_path)
                except:
                    pass
    else:
        pdf.section_header("Visual Analysis")
        pdf.cell(0, 10, "No image data provided.", 1, 1)

    # 4. Disclaimer (Bottom)
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI system and should be reviewed by a qualified pathologist. It is not a definitive diagnosis. Please consult with a medical professional for clinical correlation.")

    return pdf.output(dest='S').encode('latin-1')

def generate_public_report(data: dict, image_bytes: bytes = None) -> bytes:
    """
    Generates a patient-friendly PDF report for Clinical Screening (Model B).
    """
    # Normalize data
    if "final_analysis" in data:
        data = data["final_analysis"]

    pdf = MedicalReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # 1. Sample Info
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Screening Information", 0, 1, 'L')
    
    pdf.set_font('Arial', '', 10)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(30, 8, " Date", 1, 0, 'L', 1)
    pdf.cell(65, 8, f" {datetime.now().strftime('%Y-%m-%d')}", 1, 0, 'L')
    pdf.cell(30, 8, " Modality", 1, 0, 'L', 1)
    pdf.cell(65, 8, " Clinical Screening", 1, 1, 'L')
    
    pdf.ln(10)

    # 2. Summary
    pdf.section_header("Screening Summary")
    
    hygiene_score = data.get("hygiene_score", "Unknown")
    screening_result = data.get("screening_result", "Unknown")
    
    pdf.data_row("Screening Result", screening_result, fill=True)
    pdf.data_row("Hygiene Score", hygiene_score, fill=False)

    pdf.ln(10)

    # 3. Detailed Findings
    pdf.section_header("Detailed Findings")
    
    detections = data.get("detections", [])
    if not detections:
        pdf.cell(0, 10, "  No specific issues detected.", 1, 1)
    else:
        counts = {}
        for d in detections:
            cls = d.get("class", "Unknown")
            counts[cls] = counts.get(cls, 0) + 1
            
        for i, (cls, count) in enumerate(counts.items()):
            pdf.data_row(cls, f"{count} detected", fill=(i % 2 == 0))

    pdf.ln(10)

    # 4. Visual Screening
    if image_bytes:
        pdf.section_header("Visual Screening")
        pdf.ln(2)
        
        # Use a local temp file to avoid Windows permission/path issues with AppData
        temp_dir = os.path.join(os.getcwd(), "temp_reports")
        os.makedirs(temp_dir, exist_ok=True)
        tmp_path = os.path.join(temp_dir, f"public_{uuid.uuid4()}.jpg")
        
        try:
            # Convert image to JPEG using Pillow to ensure FPDF compatibility
            # This handles WebP, PNG, etc.
            with Image.open(io.BytesIO(image_bytes)) as img:
                # Convert to RGB (remove alpha channel if present)
                rgb_img = img.convert('RGB')
                rgb_img.save(tmp_path, format='JPEG')
                
                w, h = rgb_img.size
                aspect = h / w
            
            target_w = 120  # Reduced width
            target_h = target_w * aspect
            
            # Check if image fits on page, else add page
            if pdf.get_y() + target_h > 250: 
                pdf.add_page()
            
            # Center the image
            x_pos = (210 - target_w) / 2
            pdf.image(tmp_path, x=x_pos, w=target_w)
            pdf.ln(target_h + 5) # Move cursor past image
            
        except Exception as e:
            pdf.cell(0, 10, f"Error loading image: {str(e)}", 1, 1)
        finally:
            if os.path.exists(tmp_path):
                try:
                    os.remove(tmp_path)
                except:
                    pass

    # 5. Recommendations
    pdf.ln(10)
    pdf.section_header("Recommendations")
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 6, "Please maintain good oral hygiene by brushing twice a day and flossing. If any abnormalities were detected, we strongly recommend visiting a dentist for a physical examination.")

    return pdf.output(dest='S').encode('latin-1')
